---
- hosts: all
  sudo:  true
  roles:
    # Common packages
    - common
    - nodejs
    - supervisor
    - role: nginx
      nginx_sites: none

    # Storage
    - redis
    - mongodb
    - mysql
    - sqlite

    # PHP
    - php5-common
    - php5-fpm
    - php5-cli
    - memcached
    - composer
    - symfony
